name: Python application with Docker, Pylint and Test Coverage

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install docker.io

      - name: Build Docker image
        run: |
          mkdir -p build/
          docker build -t my-python-app:latest .

      - name: Run Docker container
        run: |
          docker run -it --rm -v $(pwd):/app my-python-app:latest

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint with pylint
        run: |
          pylint ./app

      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov=app
